/**
 * Keepsake shared types, the data model from PRD §12.
 *
 * One deliberate refinement from the PRD's illustrative interfaces
 * (allowed by §12, flagged per §0): streaks and theme rotation live
 * per-profile (`ProfileProgress`) instead of in the global AppState,
 * because FR-10 requires multiple profiles with independent data.
 */

/** A family member or important person in the patient's life. */
export interface Person {
  id: string
  name: string
  relationship: string
  notes?: string
}

/** A favorite song, stored with the extracted YouTube video id. */
export interface MusicLink {
  id: string
  title: string
  youtubeUrl: string
  videoId: string
}

/**
 * The person's favorite things (v1.1). Lane weaves these into
 * conversations and the rotating "special moment" of each visit.
 */
export interface Favorites {
  /** Teams and sports, e.g. "the Braves", "college football". */
  sports: string[]
  /** e.g. "sweet tea", "black coffee". */
  drinks: string[]
  /** e.g. "peach cobbler", "fried catfish". */
  foods: string[]
  /** Movies and shows, e.g. "westerns", "The Andy Griffith Show". */
  shows: string[]
  /** Hobbies and pastimes, e.g. "fishing", "gin rummy". */
  hobbies: string[]
}

/** Fresh empty Favorites (a function so no arrays are ever shared). */
export function emptyFavorites(): Favorites {
  return { sports: [], drinks: [], foods: [], shows: [], hobbies: [] }
}

/** One patient profile, created and edited by the caretaker. */
export interface Profile {
  id: string
  name: string
  preferredName: string
  birthYear?: number
  hometown?: string
  happyMemory?: string
  family: Person[]
  favoriteMusic: MusicLink[]
  favorites: Favorites
  lifeStory?: string
  /** Topics Lane must gently steer away from (errorless learning). */
  topicsToAvoid: string[]
  /** Gentle, reassuring facts for spaced retrieval, one restated per visit. */
  factsToReinforce: string[]
  createdAt: string // ISO
  updatedAt: string // ISO
}

/* ------------------------------ Lane learns ------------------------------ */

/** What kind of thing Lane noticed (PDR v1.2 §2.2). */
export type LearnedCategory =
  | 'hometown'
  | 'happyMemory'
  | 'food'
  | 'drink'
  | 'sport'
  | 'show'
  | 'hobby'
  | 'lifeStory'
  | 'delight'
  | 'avoid'

/**
 * A candidate fact Lane picked up during a visit (PDR v1.2 §2). Nothing
 * is ever applied to the profile until the caretaker approves it, a
 * misheard fact repeated back would be worse than no fact at all.
 */
export interface LearnedFact {
  id: string
  profileId: string
  category: LearnedCategory
  /** Short, plain phrasing suitable for the profile. */
  value: string
  /** The person's own words that support it, shown as evidence. */
  quote?: string
  sourceVisitId: string
  visitDate: string // ISO
  status: 'pending' | 'approved' | 'dismissed'
  decidedAt?: string // ISO
}

export type Role = 'lane' | 'patient'

/** One turn in a visit transcript. */
export interface Message {
  role: Role
  text: string
  /** The tap-able answer chips that were offered with a Lane message. */
  suggestions?: string[]
  ts: string // ISO
}

/** The post-visit caretaker summary (PRD §8.4). Never grades memory. */
export interface VisitSummary {
  summary: string
  engagement: number // 1-5
  highlights: string[]
  flags: string[]
  encouragement: string
  /** 'ai' when generated by Lane, 'scripted' for the no-key templated recap. */
  generatedBy: 'ai' | 'scripted'
}

/** One completed (or interrupted) daily visit. */
export interface Visit {
  id: string
  profileId: string
  date: string // ISO datetime the visit started
  mood?: number // 1-5, emoji index; undefined if interrupted before mood
  theme: string // e.g. "Childhood"
  transcript: Message[]
  summary?: VisitSummary
  /** Which gentle fact was warmly restated this visit, if any. */
  factReinforced?: string
  durationSec?: number
  completed: boolean
  /** True for caretaker "Preview Lane" runs, excluded from streaks & charts. */
  preview?: boolean
  /** 'ai' or 'scripted', which mode the conversation ran in. */
  mode?: 'ai' | 'scripted'
}

/** App settings. The API key lives ONLY here, in this browser (PRD §6). */
export interface Settings {
  apiKey?: string
  model: string
  /** SHA-256 hash of the caretaker PIN (never the raw digits, §16.6). */
  pinHash?: string
  readAloudEnabled: boolean
  /** Preferred speech-synthesis voice; unset means "auto-pick the best". */
  voiceURI?: string
}

/** Per-profile streak + theme rotation state. */
export interface ProfileProgress {
  currentStreak: number
  longestStreak: number
  /** ISO date (yyyy-mm-dd) of the last completed visit, for streak math. */
  lastVisitDate?: string
  /** Index into THEMES of the most recently used theme. */
  lastThemeIndex: number
}

/** Global app state. */
export interface AppState {
  activeProfileId?: string
}

/** In-progress visit draft, saved so an interrupted visit can resume. */
export interface VisitDraft {
  visit: Visit
  stepIndex: number
  savedAt: string
}

/** Model picker entries, current IDs verified July 2026 (PRD §12.4). */
export interface ModelOption {
  id: string
  label: string
  note: string
}

export const MODEL_OPTIONS: ModelOption[] = [
  {
    id: 'claude-haiku-4-5-20251001',
    label: 'Haiku, everyday visits (cheapest)',
    note: 'Roughly $1 in / $5 out per million tokens. A visit costs well under a cent to a few cents.',
  },
  {
    id: 'claude-sonnet-5',
    label: 'Sonnet, warmer, more natural',
    note: 'Roughly $2 in / $10 out per million tokens (intro pricing through Aug 31, 2026).',
  },
  {
    id: 'claude-opus-4-8',
    label: 'Opus, premium (rarely needed)',
    note: 'Roughly $5 in / $25 out per million tokens.',
  },
]

export const DEFAULT_MODEL = MODEL_OPTIONS[0].id
